# Generated by Django 5.2.8 on 2026-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_studentdata_aadhaar_studentdata_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='batch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
