# Generated by Django 5.2.8 on 2026-04-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_studentdata_batch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='nsqf',
            field=models.CharField(blank=True, choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6')], max_length=20, null=True),
        ),
    ]
