# Generated by Django 5.2.8 on 2026-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_studentdata_nsqf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dlc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='NsqfElectronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('nsqf_level', models.PositiveIntegerField(max_length=2)),
                ('hours', models.PositiveIntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='NsqfIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('nsqf_level', models.PositiveIntegerField(max_length=2)),
                ('hours', models.PositiveIntegerField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='qualifications',
            field=models.CharField(blank=True, choices=[('10+2 / ITI / Pursuing Graduation', '10+2 / ITI / Pursuing Graduation'), ('Graduation (B.Sc / B.Com / BA / BBA)', 'Graduation (B.Sc / B.Com / BA / BBA)'), ('Technical (CS / IT / BCA / B.Tech)', 'Technical (CS / IT / BCA / B.Tech)'), ('Post Graduate', 'Post Graduate'), ('MCA / M.Tech', 'MCA / M.Tech'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
